# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Convertion(object):
    def setupUi(self, Convertion):
        Convertion.setObjectName("Convertion")
        Convertion.resize(650, 200)
        self.centralwidget = QtWidgets.QWidget(Convertion)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 40, 165, 33))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 90, 574, 35))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftLine = QtWidgets.QLineEdit(self.widget)
        self.leftLine.setObjectName("leftLine")
        self.horizontalLayout.addWidget(self.leftLine)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.convertButton = QtWidgets.QPushButton(self.widget)
        self.convertButton.setObjectName("convertButton")
        self.horizontalLayout.addWidget(self.convertButton)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        Convertion.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Convertion)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 23))
        self.menubar.setObjectName("menubar")
        self.menupyqt5 = QtWidgets.QMenu(self.menubar)
        self.menupyqt5.setObjectName("menupyqt5")
        Convertion.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Convertion)
        self.statusbar.setObjectName("statusbar")
        Convertion.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menupyqt5.menuAction())

        self.retranslateUi(Convertion)
        QtCore.QMetaObject.connectSlotsByName(Convertion)

    def retranslateUi(self, Convertion):
        _translate = QtCore.QCoreApplication.translate
        Convertion.setWindowTitle(_translate("Convertion", "MainWindow"))
        self.label_3.setText(_translate("Convertion", "汇率转化器"))
        self.label.setText(_translate("Convertion", "USD"))
        self.convertButton.setText(_translate("Convertion", "转换"))
        self.label_2.setText(_translate("Convertion", "CNY"))
        self.menupyqt5.setTitle(_translate("Convertion", "Convertion"))
