import datetime
import numpy as np
import vertica_python

# 按照数据库基本信息填写参数
conn_info = {'host': '192.168.33.199',
             'port': 5433,
             'user': 'dbadmin',
             'password': 'oeuser123456',
             'database': 'oeuser',
             # autogenerated session label by default,
             'session_label': 'some_label',
             # default throw error on invalid UTF-8 results
             'unicode_error': 'strict',
             # SSL is disabled by default
             'ssl': False,
             # autocommit is off by default
             'autocommit': True,
             # using server-side prepared statements is disabled by default
             'use_prepared_statements': False,
             # connection timeout is not enabled by default
             # 5 seconds timeout for a socket operation (Establishing a TCP connection or read/write operation)
             'connection_timeout': 5
             }


def insertToVertica():
    with vertica_python.connect(**conn_info) as connection:
        cur = connection.cursor()
        for i in range(0, 1000000):
            number = np.arange(i * 7, i * 7 + 7)
            sql = f"""insert into testVertica (index, number1, number2, number3, number4, number5, number6) values 
            ({number[0]}, {number[1]}, {number[2]}, {number[3]}, {number[4]}, {number[5]}, {number[6]})"""
            cur.execute(sql)  # cur.execute()里放执行语句
            print(f"已插入{i}条数据~")
        cur.closed()
        connection.closed()
        print("数据操作已完成")


def queryFromVertica():
    with vertica_python.connect(**conn_info) as connection:  # 使用with...as...可以在with语句块结束后，自动关闭数据库连接
        cur = connection.cursor()
        sql = """select 
        index, 
        number1, 
        number2, 
        number3, 
        number4, 
        number5, 
        number6 
        from testVertica"""
        # sql = """select
        # number3,
        # number4,
        # number5,
        #         number6
        #         from testVertica"""
        cur.execute(sql)  # cur.execute()里放执行语句
        result = cur.fetchall()
        print(result)
        print(len(result))
        cur.closed()
        connection.closed()
        print("数据操作已完成")


if __name__ == '__main__':
    timer0 = datetime.datetime.now()
    # insertToVertica()
    queryFromVertica()
    timer1 = datetime.datetime.now()
    timer = timer1 - timer0
    hours = int(timer.seconds / 3600)
    minutes = int((timer.seconds % 3600) / 60)
    seconds = (timer.seconds % 3600) % 60

    print('运行时间：%.1fhours %.1fminutes %.1fseconds' % (hours, minutes, seconds))  # 保留小数点后一位
